use_frameworks!

inhibit_all_warnings!

source 'https://github.com/CocoaPods/Specs.git'
source 'http://git.flowever.net/component/Specs.git'

target 'Music_Example' do
  pod 'Music', :path => '../'
end
